# Generated by Django 6.0.2 on 2026-02-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('value_type', models.CharField(choices=[('int', 'int'), ('float', 'float')], default='float', max_length=10)),
                ('higher_is_better', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='UserValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.usermetric')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.item')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.metric')),
            ],
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('dataset', 'key'), name='uniq_item_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('dataset', 'key'), name='uniq_metric_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='value',
            constraint=models.UniqueConstraint(fields=('item', 'metric'), name='uniq_value_item_metric'),
        ),
    ]
