# Generated by Django 6.0.2 on 2026-02-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservalue',
            name='user_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='uservalue',
            index=models.Index(fields=['user_metric', 'user_hash', '-created_at'], name='idx_userval_hist'),
        ),
    ]
